/* eslint-disable no-restricted-globals */

// This service worker is the standard CRA PWA template pattern, using Workbox
// (already bundled with react-scripts via workbox-webpack-plugin).
// It precaches the app shell (JS/CSS/HTML) so the app loads offline, and
// uses a network-first strategy for navigation so users always get the
// latest app shell when online, falling back to cache when offline.
// API calls (/api/*) are intentionally NOT cached here — this app's data
// is business-critical and should not silently serve stale records.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all assets generated by the build process (injected by Workbox at build time).
precacheAndRoute(self.__WB_MANIFEST);

// App-shell style routing: serve index.html for navigation requests,
// excluding API calls and files with extensions (images, etc).
const fileExtensionRegexp = /\/[^/?]+\.[^/]+$/;
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.startsWith('/api/')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  createHandlerBoundToURL(`${process.env.PUBLIC_URL}/index.html`)
);

// Cache static assets (CSS/JS/images) with stale-while-revalidate.
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin &&
    (url.pathname.endsWith('.png') ||
      url.pathname.endsWith('.jpg') ||
      url.pathname.endsWith('.svg') ||
      url.pathname.endsWith('.ico')),
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  })
);

// Cache self-hosted fonts long-term (see index.html — fonts are now
// self-hosted specifically so they survive offline use).
registerRoute(
  ({ url }) => url.pathname.startsWith('/fonts/'),
  new StaleWhileRevalidate({
    cacheName: 'fonts',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 })],
  })
);

// Explicitly do NOT cache /api/* — business data must stay fresh.
// (No registerRoute for /api means these requests just hit the network,
// and the app's own UI should handle the offline/error state.)

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
